# web 服务端口
port: 3000
# chrome 的安装路径
chromePath: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
# 消息发送间隔
sendInterval: 5000
google:
  apiKey: xxxxxxxxxxxxxxxxxxxxxxxx
  model: gemini-1.5-flash
  # 是否开启 google 搜索, 返回会更精准,成本35美金/1000次
  searchEnable: false
template:
  # 变量名 使用excel的表头名称, 比如 website, companyName 等等
  prompt: |
    判断网站是否有效 -> 获取网站内容 -> 判断是否在线商店 -> 是的话则提取出主营类目
    search in english and return with json format
    input: {website}
    result example: {"is_valid": true, "is_online_store": true, "main_category": "company category, e.g. IT, at most 3 words", description: "company description"}
  # excel 表头必需包含 linkedin, 可以使用使用excel的表头名称替换变量
  message: |
    这是一个模板消息 变量替换: {website}
